apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
    tier: backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: webapp
    tier: backend